= RESTful beer catalogue API Guide
Txor;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview

This API allows to manage a beer catalogue from different manufacturers.
Beer consumers can look up the beer catalogue in order to inspire future purchases.

[[overview_http_verbs]]
== HTTP verbs
The following HTTP verbs are used in Beer API.
|===
| Verb | Usage
| `GET`
| Used to retrieve a resource
|===

[[overview_http_status_codes]]
== HTTP status codes

The following HTTP status codes are used in Beer API.

|===
| Status code | Usage
| `200 OK`
| The request completed successfully
| `404 Not Found`
| The requested resource did not exist
|===

[[resources]]
= Resources

[[resources_beers]]
== Beer list

The beer list provides information about all existing beers and its manufacturers.

[[resources_beers_access]]
=== Accessing the beer list

A `GET` request is used to access the index

operation::beer-list-example[snippets='http-request,curl-request,http-response']

[[resources_beer]]
== Beer

[[resources_beer_retrieve]]
=== Retrieve a beer

A `GET` request will retrieve the details of a beer

operation::beer-get-example[snippets='http-request,curl-request,http-response']

[[resources_manufacturers]]
== Manufacturer list

The manufacturer list provides the names of all manufacturers.

[[resources_manufacturers_access]]
=== Accessing the manufacturer list

A `GET` request is used to access the manufacturer list

operation::manufacturer-list-example[snippets='http-request,curl-request,http-response']