= RESTful beer catalogue API Guide
Txor;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[overview]]
= Overview

This API allows to manage a beer catalogue from different manufacturers.
Beer consumers can look up the beer catalogue in order to inspire future purchases.

[[overview_http_verbs]]
== HTTP verbs

The following HTTP verbs are used in Beer API.

|===
| `GET`
| Used to retrieve a resource
| `POST`
| Used to create a new resource
| `PATCH`
| Used to update an existing resource, including partial updates
| `DELETE`
| Used to delete an existing resource
|===

[[overview_http_status_codes]]
== HTTP status codes

The following HTTP status codes are used in Beer API.

|===
| `200 OK`
| The request completed successfully
| `201 Created`
| A new resource has been created successfully.
The resource's URI is available from the response's `Location` header
| `204 No Content`
| An update to an existing resource has been applied successfully
| `400 Bad Request`
| The request was malformed.
The response body will include an error providing further information
| `404 Not Found`
| The requested resource did not exist
|===

[[resources]]
= Resources

[[resources_beer]]
== Beer

[[resources_beer_name_list]]
=== Accessing the beer name list

A `GET` request is used to access the beer name list

operation::beer-list-example[snippets='http-request,http-response']

[[resources_beer_create]]
=== Create a beer

A `POST` request is used to create a beer

operation::beer-create-example[snippets='http-request,http-response']

[[resources_beer_retrieve]]
=== Retrieve a beer

A `GET` request will retrieve the details of a beer

operation::beer-get-example[snippets='http-request,http-response']

[[resources_manufacturer]]
== Manufacturer

[[resources_manufacturer_name_list]]
=== Retrieve a manufacturer name list

A `GET` request is used to access the manufacturer name list

operation::manufacturer-list-example[snippets='http-request,http-response']

[[resources_manufacturer_create]]
=== Create a manufacturer

A `POST` request is used to create a manufacturer

operation::manufacturer-create-example[snippets='http-request,http-response']

[[resources_manufacturer_retrieve]]
=== Retrieve a manufacturer

A `GET` request will retrieve the details of a manufacturer

operation::manufacturer-get-example[snippets='http-request,http-response']

[[resources_manufacturer_update]]
=== Update manufacturer information

A `PUT` request is used to update manufacturer information.

operation::manufacturer-update-example[snippets='http-request,http-response']

[[resources_manufacturer_delete]]
=== Delete manufacturer

A `DELETE` request is used to delete a manufacturer.

operation::manufacturer-delete-example[snippets='http-request,http-response']